awell-health/hosted-pages

- package.json
- src/hooks/useSessionActivities/useSessionActivities.ts
- yarn.lock
I tried to add [pollInterval](https://www.apollographql.com/docs/react/data/queries/#polling) and even added `startPolling` to manually start polling for graphql query but I wasn't able to test it. The query wasn't called again. I also tried [disabling strictReact](https://github.com/apollographql/apollo-client/issues/9819) in nextjs but that didn't help either.
So I implemented a manual `setInterval` function that refetches the graphql query after every 10 seconds and clears the interval when component/hook gets unmounted.
This temporarily fixes the issue.
> Add interval of 10 seconds to refetch SessionActivities query manually when subscription fails

- sentry.client.config.js
- src/components/ErrorBoundary/ErrorBoundary.tsx
Changes:
- added NEXT_PUBLIC_AWELL_ENVIRONMENT with environment values to various Vercel deployments (e.g. staging, sandbox, production, production-us)
- use this EnvVar in Sentry config for app to ensure that environment is correctly tagged
This is a workaround since there is no simple way to ensure that Preview builds in Vercel are not tagged as production --  NODE_ENV value (which Sentry natively relies on for tagging) in Preview builds are set to 'production' automatically 
AST-4775
> AST-4775 build(sentry): set AWELL_ENVIRONMENT var

- pages/index.tsx
- pages/l/[hostedPagesLinkId].tsx
- public/locales/en/common.json
- public/locales/et/common.json
- public/locales/fr/common.json
- public/locales/nl/common.json
- src/components/Checklist/Checklist.tsx
- src/components/ErrorBoundary/ErrorBoundary.tsx
- src/components/ErrorBoundary/index.ts
- src/components/ErrorBoundary/types.ts
- src/components/StartHostedActivitySessionFlow/StartHostedActivitySessionFlow.tsx
- src/components/StartHostedActivitySessionFlow/startHostedActivitySessionFlow.module.css
- src/config/awell.ts
- src/config/index.ts
https://www.loom.com/share/e717216d06334608970ad44c21b116a3
**In this MR:**
- Make sure all strings are translatable
- Wrap `l/[hostedPagesLinkId].tsx` page in ThemeProvider + make sure translations are loaded with `getServerSideProps`
- Add translations to ErrorBoundary
**Note:**
Not all translations in all languages are added in this MR but all keys are present in all languages so it is easy to add translations later if needed. Primary language we need to support right now is English.
> AST-4886: translations for AHP

- .github/workflows/production-deployment.yml
- .github/workflows/sandbox-deployment.yml
- .github/workflows/staging-deployment.yml
Reason:
- checkout action v2 uses node@12 which will be deprecated by github for actions this summer
Changes:
- update checkout action to v3 in all action config files (uses node@16)
- replace `mohsin` with `github bot` as user doing releases (see https://github.com/actions/checkout/pull/1184 for context)
> chore(ci): update checkout action to v3

- next-i18next.config.js
- pages/l/[hostedPagesLinkId].tsx
- src/components/NoSSR.tsx
https://github.com/i18next/next-i18next/issues/1552
This `getServerSideProps` is not working as expected. 
See these errors in Vercel logs:
```error
Error: ENOENT: no such file or directory, scandir '/var/task/public/locales/en'
at Object.readdirSync (node:fs:1438:3)
at getLocaleNamespaces (/var/task/node_modules/next-i18next/dist/commonjs/config/createConfig.js:214:16)
at /var/task/node_modules/next-i18next/dist/commonjs/config/createConfig.js:231:20
at Array.map (<anonymous>)
at getNamespaces (/var/task/node_modules/next-i18next/dist/commonjs/config/createConfig.js:230:44)
at createConfig (/var/task/node_modules/next-i18next/dist/commonjs/config/createConfig.js:271:29)
at _callee$ (/var/task/node_modules/next-i18next/dist/commonjs/serverSideTranslations.js:201:53)
at tryCatch …
```
> fix(): use getStaticProps instead of getServerSideProps in hosted pages link page

- src/components/Form/Form.tsx
Changes:
- use `activity.id` as identifier rather than `activity.object.id` (i.e. form published id) for locally stored answers
https://awellhealth.atlassian.net/browse/AST-4925
AST-4925
> AST-4925 fix(form): use activity id for local storage key

- package.json
- public/locales/en/common.json
- src/components/Activities/ActivityContainer.tsx
- src/components/Activities/ActivityDetails.tsx
- yarn.lock
Changes:
- bump ui-library to v0.1.13
- remove unused imports
- minor change to translation string for redirect
> chore(ui-library): bump ui-library to 0.1.13 and minor cleanup

- src/services/authentication/AuthenticationProvider.tsx
Changes:
- translation string is `invalid_url` not `error_invalid_url`
> fix(i18n): fix invalid url translation

- src/hooks/activityNavigation/ActivityProvider.tsx
- src/hooks/useSessionActivities/useSessionActivities.ts
Why is this change needed?: https://www.loom.com/share/d6b407d072d54d9b86b20f4830889d79
**Problem:**   
- SessionActivityUpdated event listens to the changes in `Activity`. But this has a drawback. The changes to an activity are applied one at a time. For example, when we fill a form, then a sub-activity is added to the `Activity` document. Which triggers `ActivityUpdated` event.
- At this stage when sub-activity is added, the subscription sends a message to client that this `Activity` has been updated with some new data. Client updates the cache with the new `Activity` data.
- Then the `ActivityCompleted` event is triggered as `Activity` is marked as 'Done'.
But what happens if `ActivityUpdated` event happens AFTER `ActivityCompleted` ? Then the activity is first marked as `Done` by the …
> fix: remove session activity updated event as it is not needed

- src/components/Extension/DropboxSignExtension/actions/EmbeddedSigningAction/EmbeddedSigningAction.tsx
- src/components/Extension/DropboxSignExtension/actions/EmbeddedSigningAction/hooks/useCompleteEmbeddedSigningAction.tsx
Set `signed` data point according to signing status.
**Needs handling of all events (https://github.com/hellosign/hellosign-embedded/wiki/API-Documentation-(v2)#events). Currently only `sign` event is handled.**
> DropboxSign signed data point

- src/hooks/useSessionActivities/useSessionActivities.ts
When activities are added to the session via subscription, ensure that we sort the new activities by date order as well.
closes TP-215
> TP-215 fix(activities): sort activities by date when updating via subscription

- src/services/graphql/apollo-client.ts
- yarn.lock
- set TEST_DISABLE_SUBSCRIPTIONS to true in sessionStorage to completely
disable subscriptions
Confirmation message in log:
No WS traffic when the session storage parameter is set:
> Tp-345-create-browser-test-to-replicate-failure-to-complete-form

- .github/workflows/publish-release.yml
- scripts/fail_release.sh
- scripts/publish_release.sh
updates the integration with echoeshq, includes a POST that includes a deployment status.
Once we complete above then we can review and merge.
> ci: echoeshq deployment status

- src/components/StartHostedPathwaySessionFlow/StartHostedPathwaySessionFlow.tsx
Reverting the change as it is not required
> V1C-317-fix-redirect-on-ahp

- src/hooks/useSessionActivities/graphql/OnSessionActivityExpired.graphql
- src/hooks/useSessionActivities/types.ts
- src/hooks/useSessionActivities/useSessionActivities.ts
- src/types/generated/types-orchestration.tsx
> feat: and onSessionActivityExpired subscription

- package.json
- public/locales/de/common.json
- public/locales/en/common.json
- public/locales/es/common.json
- public/locales/et/common.json
- public/locales/fr/common.json
- public/locales/nl/common.json
- public/locales/ro/common.json
- public/locales/ru/common.json
- src/components/Form/Form.tsx
- src/hooks/useSubmitForm/useSubmitForm.ts
- yarn.lock
A form activity completion is dependent on 2 mutations:
1. Evaluate Form Rules
2. Submit Form Response
Only on success of both of these mutations, we mark the activity as completed.
The blinking of last question is because of the delay between `EvaluateFormRules` and `SubmitFormResponse`. See this example:
The last question was shown just after completion of `EvaluateFormRules` mutation.
----
After adding another loader for 'Submitting Form' process, here's the result:
Instead of showing the last question again, we showed the 'Submitting form...' loader text
> V1C-205 – fix(form): show a loader when form is being submitted

- pages/api/startHostedPathwaySessionFromLink/[hostedPagesLinkId].ts
- pages/c/[hostedPagesLinkId].tsx
- src/components/StartHostedPathwaySessionFlow/StartHostedPathwaySessionFlow.tsx
Backwards compatible -> ignores query params if not provided
related to V1C-398
> V1C-398 support for passing in patient identifier in hosted pages links

- package.json
- src/hooks/useHostedSession/branding/customTheme.test.ts
- src/hooks/useHostedSession/branding/customTheme.ts
- src/hooks/useHostedSession/branding/index.ts
- src/hooks/useHostedSession/useHostedSession.ts
- yarn.lock
- exposes only getTheme function and CustomTheme type to outside world
- allows to pass in null/undefined to getTheme function
- adds tests for passing null to getTheme
- bumps ui-library version latest one with deep link support in message
> refactor: simplify how to get/parse custom theme

- pages/api/startHostedPathwaySessionFromLink/[hostedPagesLinkId].ts
- pages/c/[hostedPagesLinkId].tsx
- src/components/StartHostedPathwaySessionFlow/StartHostedPathwaySessionFlow.tsx
Because now there is no re-render, we don't start 2 careflows V1C-422
> fix: render session flow only when router isReady, no re-render

- src/components/Activities/Activities.tsx
- src/components/Activities/context/ActivityContext.ts
- src/components/Activities/context/ActivityProvider.tsx
- src/hooks/useCompleteExtensionActivity/useCompleteExtensionActivity.ts
- src/hooks/useMessage/useMessage.ts
- src/hooks/useSessionActivities/useSessionActivities.ts
- src/hooks/useSubmitChecklist/useSubmitChecklist.ts
- src/hooks/useSubmitForm/useSubmitForm.ts
Very hard to reproduce the issue. 
After playing with manually unsetting current activity I've managed to do it. Looks like there is a race condition between state update via cache and manual one.
As if when we did manual update we were not working with up to date activities array, which cause us to select same activity again.
With this PR determining what should current activity be is now driven solely by cache update, and activity can change only when actual status in activity array changes.
In addition to this polling for activities is no done on demand, only when we have no current activity. I've tested this with subscription disabled and it works fine.
Also I did a cleanup of timer we no longer need.
https://www.loom.com/share/8d479878a21044f6b65aa4f7046e2263?sid=f361fa77-c530-4ae3-b6 …
> Tp 1336 fix repeating activities

- next.config.js
- package.json
- src/utils/logging.ts
- yarn.lock
- reuse a known pattern with typedi container holding a logger
instance configured at startup time
> fix: use di to initialise the logger instance

- src/components/Form/Form.tsx
- src/hooks/useSubmitForm/useSubmitForm.ts
> TP-2035: prevent cleaning up of local storage in case of error

- pages/index.tsx
- public/locales/en/common.json
- src/hooks/useHostedSession/useHostedSession.ts
See this ticket for context: https://linear.app/awell/issue/ET-128/error-message-displayed-after-flow-completion-in-ahp-sessions
---
Summary:
- The `useHostedSession` hook uses `GetHostedSession` graphql query to fetch latest status of the hosted session.
- The query is fetched with a poll interval of 2 seconds.
- The query fails after the hosted session is completed because the access to the Awell API is revoked from the backend.
- This results in "Unauthorized" error in the AHP, which does not make sense to the user.
Solution:
- If the hosted session is complete, stop polling the `GetHostedSession` query.
- If the result of `GetHostedSession` fails because of Unauthorised error, show that the session has expired/completed instead of "Something went wrong".
> ET-128: stop polling when session is complete + change error message

- src/hooks/useHostedSession/useHostedSession.ts
After deploying #258, I did a test in development and the polling wasn't stopped after completion of the session.
We need to call `stopPolling` from the graphql query hook that explicitly stops the polling.
> ET-128: stop polling hostedSession query when session is complete

- package.json
- yarn.lock
dependencies
___
- Rolled back the version of `@awell-health/ui-library` from 0.1.72 to 0.1.71 in `package.json`.
- This change is likely intended to address issues or incompatibilities introduced in version 0.1.72.
___
<tr>
<td>
<details>
<summary><strong>package.json</strong><dd><code>Rollback `@awell-health/ui-library` dependency version</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
package.json
<li>Rolled back <code>@awell-health/ui-library</code> dependency version from 0.1.72 to <br>0.1.71.<br>
</details>
</td>
<td><a href="https://github.com/awell-health/hosted-pages/pull/292/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575 …
> rollback-ui-lib0.1.72

- package.json
- yarn.lock
dependencies
___
- Updated the `@awell-health/ui-library` dependency to version `0.1.78` in `package.json`.
___
<tr>
<td>
<details>
<summary><strong>package.json</strong><dd><code>Bump `@awell-health/ui-library` dependency version to 0.1.78</code></dd></summary>
<hr>
package.json
<li>Updated the <code>@awell-health/ui-library</code> dependency version from <code>0.1.77</code> to <br><code>0.1.78</code>.<br>
</details>
</td>
<td><a href="https://github.com/awell-health/hosted-pages/pull/296/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr> …
> bump ui-library to 0.1.78

- pages/api/sol/providers/[id]/availability.ts
- pages/api/sol/providers/index.ts
Bug fix
___
- Improved the logging mechanism by changing the log level from 'ERROR' to 'WARNING' when no data is returned from the API.
- Utilized `isEmpty` from lodash to simplify and improve the accuracy of checking for empty data responses.
- Ensured consistent handling of empty data scenarios across provider availability and provider index API endpoints.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>availability.ts</strong><dd><code>Improve logging and data check for provider availability</code>&nbsp; </dd></summary>
<hr>
pages/api/sol/providers/[id]/availability.ts
<li>Added <code>isEmpty</code> from lodash to check for empty data.<br> <li> Changed logging …
> ET-365: fix warning loggings when API returns no providers or availabilities

- package.json
dependencies
___
- Updated the `@awell-health/ui-library` dependency version in `package.json` from `0.1.83` to `0.1.84`.
___
<tr>
<td>
<details>
<summary><strong>package.json</strong><dd><code>Update `@awell-health/ui-library` dependency version</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
package.json
<li>Updated <code>@awell-health/ui-library</code> dependency version from <code>0.1.83</code> to <br><code>0.1.84</code>.<br>
</details>
</td>
<td><a href="https://github.com/awell-health/hosted-pages/pull/311/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr> …
> Bump ui library to v84

- src/hooks/useSubmitForm/utils.ts
Enhancement, Bug fix
Show a better error message when the backend fails to submit a form.
___
- Enhanced error message to include invalid data point details.
- Improved clarity by specifying data point type and value.
- Utilized `lodash`'s `isNil` for null/undefined checks.
___
<tr>
<td>
<details>
<summary><strong>utils.ts</strong><dd><code>Enhanced error handling for invalid data points</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/hooks/useSubmitForm/utils.ts
<li>Enhanced error message to include invalid data point details.<br> <li> Added logic to handle <code>dataPointValueType</code> and …
> Improve error message on AHP so we can see which datapoints are invalid

- src/components/Activities/context/ActivityProvider.tsx
- src/hooks/useCompleteSession/CompleteSession.graphql
- src/hooks/useCompleteSession/index.ts
- src/hooks/useCompleteSession/types.ts
- src/hooks/useCompleteSession/useCompleteSession.ts
- src/hooks/useSessionActivities/useSessionActivities.ts
- src/types/generated/fragment-types.ts
- src/types/generated/types-orchestration.tsx
Once the hosted pages application knows the individual activity has been completed, we want to manually call the `CompleteSession` mutation in order to "force" the redirect to success_url
> feat(session): complete single-activity sessions manually
