- package.json
Implements https://awellhealth.atlassian.net/browse/AST-4549 which is fixed in the UI library.
> AST:4549: bump version of UI library

- package.json
- yarn.lock
> bump ui-library version to 0.0.46

- package.json
- pages/index.tsx
- public/locales/en/common.json
- public/locales/et/common.json
- public/locales/fr/common.json
- public/locales/nl/common.json
Can only be merged when https://github.com/awell-health/ui-library/pull/30 is merged.
> AST-4622: confirmation modal when closing hosted pages app

- sentry.client.config.js
- yarn.lock
Changes:
Add session replay config to sentry client config
- sample 10% of all sessions
- sample 100% of all error sessions
- mask all text and inputs
> feat(sentry): add session replay config to sentry

- pages/index.tsx
Changes:
- typeof window must be a string
> fix(index): undefined type fix for window object

- pages/_app.tsx
- pages/index.tsx
- pages/preview.tsx
- public/locales/en/common.json
- src/layouts/HostedSessionLayout.tsx
- src/layouts/index.tsx
- styles/Home.module.css
https://awellhealth.atlassian.net/browse/AST-4863
https://www.loom.com/share/33c9d75f5f7c4974a1ac2a76682f3f23
Clicking "Start preview" will work as soon as https://awellhealth.atlassian.net/browse/AST-4864 is fixed.
> AST-4863: add preview page in Awell Hosted Pages

- pages/index.tsx
- public/locales/en/common.json
- src/assets/cancel.svg
- src/assets/success.svg
- src/components/CancelPage/CancelPage.tsx
- src/components/CancelPage/cancelPage.module.css
- src/components/CancelPage/index.ts
- src/components/SuccessPage/SuccessPage.tsx
- src/components/SuccessPage/index.ts
- src/components/SuccessPage/successPage.module.css
- src/types/generated/types-orchestration.tsx
Demo: https://www.loom.com/share/59b8d32d3cc243e595be0772568d902f
> AST-4850: Add SuccessPage and CancelPage in case when success_url or cancel_url are unavailable

- package.json
- src/components/Activities/ActivityContainer.tsx
- src/components/Checklist/Checklist.tsx
- src/components/Checklist/checklist.module.css
- src/components/ErrorBoundary/ErrorBoundary.tsx
- src/components/ErrorBoundary/types.ts
- src/components/Message/Message.tsx
- src/layouts/HostedSessionLayout.tsx
- styles/globals.css
- yarn.lock
https://www.loom.com/share/fee7ef439e5b400ab5ca07fd7d27d18c
> AST-4868: implement ui-lib v0.52

- package.json
- src/components/Extension/utils.ts
- src/hooks/useExtensionActivity/types.ts
- src/hooks/useExtensionActivity/useExtensionActivity.ts
- src/hooks/useForm/graphql/Question.graphql
- src/hooks/useForm/useForm.ts
- src/types/generated/fragment-types.ts
- src/types/generated/types-orchestration.tsx
- yarn.lock
Changes:
- latest lib enables select option for multiple choice, and phone number input
> AST-4990: use latest ui-library v0.0.62

- .github/release-drafter-config.yaml
- .github/workflows/production-deployment.yml
- .github/workflows/release-drafter.yaml
- .github/workflows/sandbox-deployment.yml
- .github/workflows/staging-deployment.yml
- package.json
- public/locales/en/common.json
- src/components/Form/Form.tsx
- yarn.lock
Changes:
- use v0.1.3 UI library release (https://github.com/awell-health/ui-library/releases/tag/v0.1.3)
- add release drafter and update release triggers
> feat(): use latest UI library

- package.json
- yarn.lock
🐛 Bug Fixes
AST-5003 fix(date-picker): replace date picker with input field @rahulkeerthi (https://github.com/awell-health/ui-library/pull/57)
AST-5056 fix(question): validate partial phone number for optional questions @rahulkeerthi (https://github.com/awell-health/ui-library/pull/56)
> release(0.0.42): bump ui library to 0.1.4

- .env.sandbox.example
Changes:
- add an .env.sandbox.example file that includes config (except JWT config) for connecting a local development app to your Awell Sandbox environment
> chore(env): add sandbox example env file

- package.json
- yarn.lock
Changes:
- package version -> 0.0.47
- awell-health/ui-library package -> 0.1.7
> chore(): bump ui library ver to 0.1.7, package ver to 0.0.47

- package.json
- yarn.lock
Changes:
- bump ui-lib to 0.1.10
- bump package version to 0.0.48
closes AST-5323
> chore(): bump ui-lib and package version

- package.json
- yarn.lock
Changes:
- bump ui-library to 0.1.11
- bump package version to 0.0.49
> chore(release): v0.0.49

- public/locales/en/common.json
Reverts awell-health/hosted-pages#127
> Revert "DRAFT - Update English translation for loading activities"

- src/hooks/useCompleteExtensionActivity/useCompleteExtensionActivity.ts
- src/hooks/useMessage/useMessage.ts
- src/hooks/useSubmitChecklist/useSubmitChecklist.ts
- src/hooks/useSubmitForm/useSubmitForm.ts
- yarn.lock
https://www.loom.com/share/3a4d04235de949caa7f145ef468e873e?sid=fcd381c1-e7cb-4a99-a478-50c7c7334142
> fix: refetch HostedSessionActivities on submission of activities 

- package.json
- src/components/Form/Form.tsx
- src/hooks/useForm/graphql/Form.graphql
- src/hooks/useHostedSession/graphql/getHostedSession.graphql
- src/types/generated/types-orchestration.tsx
- yarn.lock
Changes:
- add form autosave prop
- add trademark to form graphql
- bump package version
closes V1C-62 and V1C-60
> feat(form): add trademark, autosave setting, bump version

- pages/index.tsx
- sentry.client.config.js
- sentry.server.config.js
- src/components/AuthGuard.tsx
- src/components/Form/Form.tsx
- src/services/ErrorReporter/addSentryBreadcrumb.ts
- src/services/ErrorReporter/index.ts
- src/services/ErrorReporter/masker.ts
- src/services/authentication/AuthenticationProvider.tsx
Changes:
- update sentry client config
- mask inputs rather than all text
> chore(sentry): include request and response headers and request bodies

- package.json
- yarn.lock
Changes:
- version bump
- update ui-library to latest
> Bump version to 0.0.73

- package.json
- yarn.lock
Disable buttons on forms after submitting to prevent duplicated submissions.
https://www.loom.com/share/42f21d0aae7b45e2b3e95d180d479317?sid=c6d17200-f61c-46d4-81df-5cbeb74877f3
> Bump ui library to 0.1.30

- package.json
- public/locales/de/common.json
- public/locales/en/common.json
- public/locales/es/common.json
- public/locales/et/common.json
- public/locales/fr/common.json
- public/locales/nl/common.json
- public/locales/ro/common.json
- public/locales/ru/common.json
- src/components/Form/Form.tsx
- src/hooks/useForm/graphql/Question.graphql
- src/types/generated/types-orchestration.tsx
- yarn.lock
Do not merge before: https://github.com/awell-health/ui-library/pull/136
> TP-1300: Implement date validation in Hosted Pages

- next.config.js
- package.json
- src/utils/logging.ts
- yarn.lock
ensure we dont have exceptions when the logger is not enabled
> fix(logging): Replace logging initalization strategy

- public/locales/en/common.json
- src/components/Checklist/Checklist.tsx
- src/components/Form/Form.tsx
- src/components/Message/Message.tsx
- src/hooks/useHostedSession/branding/customTheme.test.ts
- src/hooks/useHostedSession/branding/customTheme.ts
Sol would like to customize the form navigation buttons and message CTA.
Documentation added [here](https://www.notion.so/awellhealth/Custom-theming-for-Hosted-Pages-9005d4ef3d1644bd984f687471b68348?pvs=4).
> TP-2492: addtl custom theming

- package.json
- src/types/generated/fragment-types.ts
- src/types/generated/types-orchestration.tsx
- yarn.lock
Context here: https://linear.app/awell/issue/ET-217/add-email-validation-to-forms
> ET-217: copy schema + update ui-library

- package.json
- pages/api/sol/appointments.ts
- pages/api/sol/providers/[id]/availability.ts
- pages/api/sol/providers/index.ts
- src/components/Extension/PrivateExtensions/actions/IntakeScheduling/IntakeScheduling.tsx
- src/components/Extension/PrivateExtensions/actions/IntakeScheduling/api.service.ts
- src/components/Extension/PrivateExtensions/actions/IntakeScheduling/helpers/error.ts
- src/components/Extension/PrivateExtensions/actions/IntakeScheduling/hooks/useIntakeScheduling.tsx
- yarn.lock
requires the updated sol scheduling package with the appropriate types. some basic functionality to call the fetchProvidersFn when preferences are updated
> feat(intake-scheduling): Updated to support provider preferences and additional onComplete datapoints

- src/components/Extension/PrivateExtensions/actions/IntakeScheduling/IntakeScheduling.tsx
- src/components/Extension/PrivateExtensions/actions/IntakeScheduling/hooks/useIntakeScheduling.tsx
enhancement
___
- Refactored the `IntakeScheduling` component to simplify state management and update effect dependencies.
- Enhanced the `completeActivity` function to include `patientTimezone` for better time zone handling.
- Simplified the `useIntakeScheduling` hook by removing unused properties and adding `patientTimezone` to the submission data.
___
<tr>
<td>
<details>
<summary><strong>IntakeScheduling.tsx</strong><dd><code>Refactor and enhance IntakeScheduling component logic</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/components/Extension/PrivateExtensions/actions/IntakeScheduling/IntakeScheduling.tsx
<li>Removed unused …
> ET-250: finalize intake scheduling

- package.json
- pages/api/sol/providers/[id]/index.ts
- pages/api/sol/utils.ts
- src/components/Extension/PrivateExtensions/actions/IntakeScheduling/IntakeScheduling.tsx
- src/components/Extension/PrivateExtensions/actions/IntakeScheduling/api.service.ts
- yarn.lock
enhancement, dependencies
___
- Implemented a new API handler for fetching provider details, including error handling for non-GET requests and failed fetch responses.
- Added `GET_PROVIDER` to `API_METHODS` enum and defined the route for fetching provider information in `API_ROUTES`.
- Integrated provider fetching functionality in the `IntakeScheduling` component, updating types for slots and preferences.
- Implemented `fetchProvider` function in the API service with schema validation for provider response.
- Updated `@awell-health/sol-scheduling` dependency to version 0.2.14.
___
<tr>
<td>
<details>
<summary><strong>index.ts</strong><dd><code>Add API …
> chore(): implement sol-scheduling v14

- pages/api/sol/providers/index.ts
- src/utils/getAccessToken.ts
enhancement, bug fix
___
- Added a logging helper function to facilitate sending logs to an API route, enhancing the monitoring capabilities.
- Improved error response in the `sol/providers` API by adding a `message` field, providing more detailed information on failures.
- Implemented error handling for logging requests to ensure robustness in the logging process.
___
<tr>
<td>
<details>
<summary><strong>index.ts</strong><dd><code>Improve error response with additional message field</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
pages/api/sol/providers/index.ts
<li>Added a <code>message</code> field to the error response.<br> <li> Enhanced …
> add-sol-logging

- src/components/Extension/ShellyExtension/actions/ReviewMedicationExtraction/ReviewMedicationExtraction.module.css
- src/components/Extension/ShellyExtension/actions/ReviewMedicationExtraction/ReviewMedicationExtraction.tsx
- Convert the medication review component into a HTML table.
- Add header with the extracted labels.
- Use Prescribable Name instead of dosage form name.
___
enhancement
___
- Converted the medication review component into an HTML table for better organization and readability.
- Added a new field `prescribable_name` to the medication data structure, replacing `dose_form_name`.
- Updated the CSS to style the new table layout, including responsive design for smaller screens.
- Enhanced the medication handling logic to accommodate the new data structure and display format.
___
<tr>
<td>
<details>
<summary><strong>ReviewMedicationExtraction.tsx</strong><dd><co …
> feat(extension): add header to medication extraction review component

- package.json
- yarn.lock
dependencies
___
- Updated the version of the `@awell-health/sol-scheduling` dependency from `0.2.14` to `0.2.17` in `package.json`.
___
<tr>
<td>
<details>
<summary><strong>package.json</strong><dd><code>Update dependency version for @awell-health/sol-scheduling</code></dd></summary>
<hr>
package.json
<li>Updated the version of <code>@awell-health/sol-scheduling</code> from <code>0.2.14</code> to <br><code>0.2.17</code>.<br>
</details>
</td>
<td><a href="https://github.com/awell-health/hosted-pages/pull/279/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr> …
> bump the version

- package.json
- yarn.lock
dependencies
___
- Updated the `@awell-health/sol-scheduling` package version from `0.2.18` to `0.2.20` in `package.json`.
___
<tr>
<td>
<details>
<hr>
package.json
<li>Updated the version of <code>@awell-health/sol-scheduling</code> from <code>0.2.18</code> to <br><code>0.2.20</code>.<br>
</details>
</td>
<td><a href="https://github.com/awell-health/hosted-pages/pull/280/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr> …
> bump the version of sol scheduling

- package.json
- yarn.lock
dependencies
___
- Updated the `@awell-health/sol-scheduling` package to version "0.2.21" in `package.json`.
___
<tr>
<td>
<details>
<hr>
package.json
<li>Updated the version of <code>@awell-health/sol-scheduling</code> from "0.2.20" to <br>"0.2.21".<br>
</details>
</td>
<td><a href="https://github.com/awell-health/hosted-pages/pull/281/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    
___
> 💡 …
> release-sol-scheduling-2.21

- package.json
- pages/api/sol/providers/[id]/availability.ts
- pages/api/sol/providers/index.ts
- yarn.lock
enhancement, bug fix
___
- Enhanced error handling in the API endpoints for providers and availability by checking for empty string responses and returning a 404 status with an empty data array.
- Added logging capability to the availability API for improved traceability.
- Updated the `@awell-health/sol-scheduling` package to version 0.2.23 in `package.json`.
___
<tr>
<td>
<details>
<summary><strong>availability.ts</strong><dd><code>Improve error handling and logging in availability API</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
pages/api/sol/providers/[id]/availability.ts
<li>Added logging import for better traceability.<br> <li> Enhanced error …
> bump(sol): 0.2.23

- package.json
- yarn.lock
dependencies
___
- Updated the `@awell-health/sol-scheduling` package to version `0.3.0` in `package.json`.
___
<tr>
<td>
<details>
<summary><strong>package.json</strong><dd><code>Update `@awell-health/sol-scheduling` dependency to version 0.3.0</code></dd></summary>
<hr>
package.json
<li>Updated the <code>@awell-health/sol-scheduling</code> dependency version from <br><code>0.2.24</code> to <code>0.3.0</code>.<br>
</details>
</td>
<td><a href="https://github.com/awell-health/hosted-pages/pull/284/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr> …
> bump(sol): 0.3.0

- package.json
- pages/api/sol/providers/index.ts
- src/components/Extension/PrivateExtensions/actions/IntakeScheduling/IntakeScheduling.tsx
- src/components/Extension/PrivateExtensions/actions/IntakeScheduling/types.ts
- src/utils/logging.ts
- yarn.lock
bumping sol api to support a broader set of therapeutic modality preferences, while still keeping the api between the hosted pages and sol backends consistent
___
enhancement, bug fix
___
- Enhanced error logging in the provider API handler by adding detailed response information and utilizing a logging utility.
- Updated therapeutic modality type in the IntakeScheduling component to use schema inference, improving type safety.
- Expanded options for therapeutic modality and delivery method preferences in the IntakeScheduling types.
- Improved the logging function to handle optional error parameters and enhanced console logging for missing logger instances.
- Bumped the `@awell-health/sol-scheduling` package version to 0.3.1 to incorporate the latest features and improvements.
___ …
> bump(sol): 0.3.1

- package.json
- pages/api/sol/providers/index.ts
- src/components/Extension/PrivateExtensions/actions/IntakeScheduling/IntakeScheduling.tsx
- src/components/Extension/PrivateExtensions/actions/IntakeScheduling/api.service.ts
- yarn.lock
enhancement, bug fix
___
- Enhanced logging in the provider API to include body parsing and error details.
- Fixed asynchronous handling in provider fetching functions to ensure they wait for results.
- Improved logging in the API service to include the number of results returned.
- Updated the `@awell-health/sol-scheduling` dependency to a newer version.
___
<tr>
<td>
<details>
<summary><strong>index.ts</strong><dd><code>Enhance logging for provider API requests and errors</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
pages/api/sol/providers/index.ts
<li>Added logging for body parsing and error handling.<br> <li> Improved error logging …
> fix the functions to wait to the result

- package.json
- yarn.lock
dependencies
___
- Updated the `@awell-health/sol-scheduling` package to version 0.3.8 in `package.json`.
___
<tr>
<td>
<details>
<summary><strong>package.json</strong><dd><code>Update `@awell-health/sol-scheduling` dependency version to 0.3.8</code></dd></summary>
<hr>
package.json
<li>Updated the version of <code>@awell-health/sol-scheduling</code> from 0.3.7 to <br>0.3.8.<br>
</details>
</td>
<td><a href="https://github.com/awell-health/hosted-pages/pull/288/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    
___
> 💡 …
> release-sol-scheduling-0.3.8

- package.json
- yarn.lock
dependencies
___
- Updated the `@awell-health/ui-library` dependency version from `0.1.71` to `0.1.72` in `package.json`.
___
<tr>
<td>
<details>
<summary><strong>package.json</strong><dd><code>Bump `@awell-health/ui-library` dependency version</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
package.json
<li>Updated the version of <code>@awell-health/ui-library</code> from <code>0.1.71</code> to <code>0.1.72</code>.<br> <br>
</details>
</td>
<td><a href="https://github.com/awell-health/hosted-pages/pull/290/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr> …
> bump ui-kit version

- package.json
- yarn.lock
https://www.loom.com/share/31ce40ee7e164d14ba387841760bfd5b
___
enhancement, dependencies
___
- Updated the `@awell-health/ui-library` dependency in `package.json` from version `0.1.71` to `0.1.74`.
- This update likely includes enhancements or bug fixes provided by the new version of the library.
___
<tr>
<td>
<details>
<summary><strong>package.json</strong><dd><code>Update `@awell-health/ui-library` to version 0.1.74</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
package.json
<li>Updated the <code>@awell-health/ui-library</code> dependency version from <code>0.1.71</code> to <br><code>0.1.74</code>.<br>
</details>
</td>
<td><a …
> bump ui lib to 1.74

- package.json
- yarn.lock
dependencies
___
- Updated the `@awell-health/sol-scheduling` package to version `0.3.10` in `package.json`.
___
<tr>
<td>
<details>
<hr>
package.json
<li>Updated the version of <code>@awell-health/sol-scheduling</code> from <code>0.3.9</code> to <br><code>0.3.10</code>.<br>
</details>
</td>
<td><a href="https://github.com/awell-health/hosted-pages/pull/294/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr> …
> release-sol-scheduling-3.10

- package.json
- yarn.lock
enhancement, dependencies
___
- Updated the `@awell-health/ui-library` dependency to version 0.1.80 to incorporate the latest enhancements and fixes.
- Updated the `@awell-health/sol-scheduling` dependency to version 0.3.13 to ensure compatibility and leverage new features.
___
PRDescriptionHeader.CHANGES_WALKTHROUGH
<tr>
<td>
<details>
<summary><strong>package.json</strong><dd><code>Update dependencies for UI library and scheduling</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
package.json
<li>Updated the version of <code>@awell-health/ui-library</code> from 0.1.78 to 0.1.80.<br> <li> Updated the version of …
> bump version of sol-scheduling & ui-kit

- package.json
- yarn.lock
dependencies
___
- Updated the `@awell-health/sol-scheduling` package to version 0.3.15 in `package.json`.
___
<tr>
<td>
<details>
<summary><strong>package.json</strong><dd><code>Update `@awell-health/sol-scheduling` dependency version to 0.3.15</code></dd></summary>
<hr>
package.json
<li>Updated the version of <code>@awell-health/sol-scheduling</code> from 0.3.13 to <br>0.3.15.<br>
</details>
</td>
<td><a href="https://github.com/awell-health/hosted-pages/pull/300/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    
___
> 💡 …
> release-sol-scheduling-0.3.15

- package.json
- yarn.lock
dependencies
___
- Updated the `@awell-health/sol-scheduling` package to version 0.3.16 in the `package.json` file.
___
<tr>
<td>
<details>
<hr>
package.json
<li>Updated the version of <code>@awell-health/sol-scheduling</code> from 0.3.15 to <br>0.3.16.<br>
</details>
</td>
<td><a href="https://github.com/awell-health/hosted-pages/pull/301/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    
___
> 💡 …
> release-sol-scheduling-0.3.16

- pages/api/sol/appointments.ts
- pages/api/sol/providers/[id]/availability.ts
- pages/api/sol/providers/[id]/index.ts
- pages/api/sol/providers/index.ts
- src/components/Extension/PrivateExtensions/actions/IntakeScheduling/IntakeScheduling.tsx
- src/components/Extension/PrivateExtensions/actions/IntakeScheduling/api.service.ts
enhancement
___
- Enhanced logging across multiple API endpoints by adding session and pathway IDs to provide better context.
- Updated API request handling to include `logContext` for improved logging and debugging.
- Integrated `useHostedSession` hook to manage session context within the `IntakeScheduling` component.
- Modified API service functions to append session and pathway information to requests.
___
<tr>
<td>
<details>
<summary><strong>appointments.ts</strong><dd><code>Enhance logging with session and pathway context</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
pages/api/sol/appointments.ts
<li>Added …
> ET-364: add session and pathway ID to the logs for context

- package.json
- public/locales/en/common.json
- public/locales/es/common.json
- public/locales/et/common.json
- public/locales/fr/common.json
- public/locales/nl/common.json
- public/locales/ro/common.json
- public/locales/ru/common.json
- src/components/Form/Form.tsx
- yarn.lock
enhancement, documentation
___
- Added new translation keys for ICD-10 catalogue descriptions and links in multiple languages.
- Enhanced the form component with additional placeholders for ICD search.
- Updated `@awell-health/ui-library` dependency version to 0.1.83.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>1 files</summary><table>
<tr>
<td>
<details>
<summary><strong>Form.tsx</strong><dd><code>Add ICD-10 related translations to Form component</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/components/Form/Form.tsx
<li>Added new translation keys for ICD-10 catalogue descriptions and <br>links.<br> <li> Enhanced the form component with …
> ET-379: bump ui-library and add translation for ICD question

- package.json
- yarn.lock
dependencies
___
- Updated the `@awell-health/sol-scheduling` package version in `package.json` from `0.3.16` to `0.3.20`.
___
<tr>
<td>
<details>
<hr>
package.json
<li>Updated the <code>@awell-health/sol-scheduling</code> dependency version from <br><code>0.3.16</code> to <code>0.3.20</code>.<br>
</details>
</td>
<td><a href="https://github.com/awell-health/hosted-pages/pull/305/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr> …
> release-sol-scheduling-0.3.20

- package.json
- yarn.lock
dependencies
___
- Updated the `@awell-health/sol-scheduling` package to version `0.3.21` in `package.json`.
___
<tr>
<td>
<details>
<hr>
package.json
<li>Updated the version of <code>@awell-health/sol-scheduling</code> from <code>0.3.20</code> to <br><code>0.3.21</code>.<br>
</details>
</td>
<td><a href="https://github.com/awell-health/hosted-pages/pull/306/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr>
___
> 💡 …
> release-sol-scheduling-0.3.21

- package.json
- yarn.lock
dependencies
___
- Updated the `@awell-health/sol-scheduling` package to version 0.3.22 in `package.json`.
___
<tr>
<td>
<details>
<hr>
package.json
<li>Updated the version of <code>@awell-health/sol-scheduling</code> from 0.3.21 to <br>0.3.22.<br>
</details>
</td>
<td><a href="https://github.com/awell-health/hosted-pages/pull/307/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr>
___
> 💡 **PR-Agent usage**: Comment …
> ET-454-release-sol-scheduling-0.3.22

- package.json
- yarn.lock
dependencies
___
- Updated the `@awell-health/sol-scheduling` package to version 0.3.23 in `package.json`.
___
<tr>
<td>
<details>
<hr>
package.json
<li>Updated the version of <code>@awell-health/sol-scheduling</code> from 0.3.22 to <br>0.3.23.<br>
</details>
</td>
<td><a href="https://github.com/awell-health/hosted-pages/pull/308/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr>
___
> 💡 **PR-Agent usage**: Comment …
> ET-454-release-sol-scheduling-0.3.23

- package.json
- yarn.lock
dependencies
___
- Updated the `@awell-health/sol-scheduling` dependency in `package.json` from version `0.3.23` to `0.3.24`.
___
<tr>
<td>
<details>
<hr>
package.json
<li>Updated the <code>@awell-health/sol-scheduling</code> dependency version from <br><code>0.3.23</code> to <code>0.3.24</code>.<br>
</details>
</td>
<td><a href="https://github.com/awell-health/hosted-pages/pull/309/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr> …
> ET-454-release-sol-scheduling-0.3.24

- package.json
- yarn.lock
enhancement, dependencies
___
- Updated the `@awell-health/sol-scheduling` package to version 0.3.28 to incorporate the latest features and fixes.
- Downgraded the `@awell-health/ui-library` package to version 0.1.83, potentially to address compatibility or stability issues.
___
<tr>
<td>
<details>
<summary><strong>package.json</strong><dd><code>Update dependencies for sol-scheduling and ui-library</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
package.json
<li>Updated <code>@awell-health/sol-scheduling</code> dependency to version 0.3.28.<br> <li> Downgraded <code>@awell-health/ui-library</code> dependency to version 0.1.83.<br>
</details>
</td> …
> ET-454-release-sol-scheduling-0.3.28

- package.json
- yarn.lock
dependencies
___
- Updated the `@awell-health/sol-scheduling` package to version `0.3.29` in `package.json`.
___
<tr>
<td>
<details>
<summary><strong>package.json</strong><dd><code>Update `@awell-health/sol-scheduling` dependency version to 0.3.29</code></dd></summary>
<hr>
package.json
<li>Updated the version of <code>@awell-health/sol-scheduling</code> from <code>0.3.28</code> to <br><code>0.3.29</code>.<br>
</details>
</td>
<td><a href="https://github.com/awell-health/hosted-pages/pull/313/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr>
___
> …
> ET-454-release-sol-scheduling-0.3.29

- pages/api/sol/providers/index.ts
- yarn.lock
i'm pushing this fix (rather than in sol-scheduling, which is where it belongs) to save a little time
> fix(sol): providers request shouldn't contain empty strings

- src/components/Extension/PrivateExtensions/WP/RequestingProviderLookUp/RequestingProviderLookUp.tsx
https://www.loom.com/share/827d53a18bd44804a5afab052d961a6c?sid=b9398941-cb6d-40eb-be0e-9613a478e4df
Bug fix, Enhancement
___
- Added a new `ErrorType` type to categorize errors as 'required' or 'api' for better error handling.
- Enhanced the logic to determine if the provider field is mandatory (`isRequired`) based on the `required` flag and the presence of API errors.
- Improved user feedback by providing detailed error messages for API failures, including guidance on how to proceed.
- Updated the `mandatory` property and error display logic to align with the new error handling approach.
- Ensured that the error state is reset before fetching providers to avoid stale error messages.
___
<table><thead><tr><th></th><th align="left">Relevant …
> ET-569: don't make q required if api fails

- package.json
- yarn.lock
dependencies
___
- Updated the `@awell-health/ui-library` dependency version in `package.json` from `0.1.86` to `0.1.87`.
- Ensures the project uses the latest features and fixes provided by the updated library version.
___
<tr>
<td>
<details>
<summary><strong>package.json</strong><dd><code>Update `@awell-health/ui-library` dependency version to 0.1.87</code></dd></summary>
<hr>
package.json
<li>Updated the version of the <code>@awell-health/ui-library</code> dependency from <br><code>0.1.86</code> to <code>0.1.87</code>.<br>
</details>
</td>
<td><a href="https://github.com/awell-health/hosted-pages/pull/320/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b2 …
> Update ui library version 0.1.87

- next-i18next.config.js
- public/locales/pl/common.json
Enhancement
___
- Added support for the Polish language in the application.
- Updated the `next-i18next.config.js` file to include 'pl' in the supported locales.
- Introduced a new JSON file (`common.json`) under `public/locales/pl` with Polish translations for various application strings.
___
<tr>
<td>
<details>
<summary><strong>next-i18next.config.js</strong><dd><code>Add Polish language support to locales configuration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
next-i18next.config.js
<li>Added 'pl' (Polish) to the list of supported locales in the <code>locales</code> <br>array.<br>
</details>
</td>
<td><a …
> ET-630: add support for Polish

- package.json
- yarn.lock
- Bump @awell-health/ui-library to version 0.1.96 in package.json and yarn.lock
- Update resolved URL and integrity hash in yarn.lock
> chore(deps): update @awell-health/ui-library to version 0.1.96

- package.json
- yarn.lock
awell-health/design-system to version 0.12.62
- Bump @awell-health/ui-library to version 0.1.97 in package.json and yarn.lock
- Update @awell-health/design-system to version 0.12.62 in yarn.lock
- Update resolved URLs and integrity hashes in yarn.lock
> chore(deps): update @awell-health/ui-library to version 0.1.97

- package.json
- yarn.lock
- Bump @awell-health/ui-library to version 0.1.98 in package.json and yarn.lock
- Update resolved URLs and integrity hashes in yarn.lock
> chore(deps): update @awell-health/ui-library to version 0.1.98

- package.json
- yarn.lock
Enhancement
___
- Bump `@awell-health/sol-scheduling` to v0.4.2
___
<tr>
<td>
<details>
<summary><strong>package.json</strong><dd><code>Bump sol-scheduling dependency</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
package.json
- Updated `@awell-health/sol-scheduling` version to `0.4.2`
</details>
</td>
<td><a href="https://github.com/awell-health/hosted-pages/pull/369/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b648 …
> release sol-scheduling 0.4.2

- package.json
- yarn.lock
Enhancement, Other
___
- Bump `@awell-health/ui-library` to 0.1.120
- Align release branch with new UI library version
___
```mermaid
flowchart LR
pkg["package.json dependencies"] -- "update version" --> ui["@awell-health/ui-library 0.1.120"]
```
<tr>
<td>
<details>
<summary><strong>package.json</strong><dd><code>Bump UI library dependency version</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
package.json
<ul><li>Updated dependency …
> release-ui-library-120

- package.json
Enhancement, Dependencies
___
- Bump `@awell-health/sol-scheduling` to 0.4.14
- Maintain existing build and scripts
___
```mermaid
flowchart LR
pkg["package.json dependencies"] -- "upgrade" --> sol["@awell-health/sol-scheduling 0.4.14"]
```
<tr>
<td>
<details>
<summary><strong>package.json</strong><dd><code>Upgrade sol-scheduling dependency to 0.4.10</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
package.json
<ul><li>Update <code>@awell-health/sol-scheduling</code> from 0.4.3 to 0.4.14.<br> <li> No other scripts or …
> chore(deps): bump sol-scheduling

- package.json
Enhancement
___
- Bump sol-scheduling to 0.4.18
___
```mermaid
flowchart LR
pkg["package.json dependency"]
sched["@awell-health/sol-scheduling"]
verOld["0.4.14"]
verNew["0.4.18"]
pkg -- "updates" --> sched
sched -- "version" --> verNew
verOld -- "replaced by" --> verNew
```
<tr>
<td>
<details>
<summary><strong>package.json</strong><dd><code>Bump sol-scheduling dependency version</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
package.json
<ul><li>Update dependency …
> chore(deps): update @awell-health/sol-scheduling to version 0.4.18

- package.json
- yarn.lock
dependencies
___
- Bump `@awell-health/ui-library` to 0.1.121
___
```mermaid
flowchart LR
pkg["package.json dependencies"] -- "bump" --> ui["@awell-health/ui-library 0.1.121"]
```
<tr>
<td>
<details>
<summary><strong>package.json</strong><dd><code>Bump UI library dependency version</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
package.json
<ul><li>Update dependency <code>@awell-health/ui-library</code> from 0.1.120 to 0.1.121</ul>
</details>
</td>
<td><a …
> release-ui-library-121
